
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xb1\xcc9-\x9e\xf8I\x9b\xa0\xb7\xee\x03\xc0\x06;\xad'
    
_lr_action_items = {u'TEXT':([0,3,7,9,15,16,17,18,19,20,21,22,23,24,27,28,],[3,3,3,3,-19,-21,-25,-24,-20,-22,-23,3,-17,-18,3,3,]),u'ONLY_FIRST':([0,1,3,6,7,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,26,28,31,32,34,],[-27,-11,-27,-10,-27,-27,-8,-6,29,-26,-19,-21,-25,-24,-20,-22,-23,-27,-17,-18,-7,-27,-12,-9,-5,]),u'PLUS_DESCENDANTS':([0,1,3,6,7,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,26,28,31,32,34,],[-27,-11,-27,-10,-27,-27,-8,-6,30,-26,-19,-21,-25,-24,-20,-22,-23,-27,-17,-18,-7,-27,-12,-9,-5,]),u'UNIQUEID':([0,7,9,27,28,],[8,8,8,8,8,]),u'NEQ':([2,4,5,6,8,],[-15,24,-14,-13,-16,]),u'GEQ':([2,4,5,6,8,],[-15,15,-14,-13,-16,]),u'LE':([2,4,5,6,8,],[-15,16,-14,-13,-16,]),u'RPAREN':([1,3,6,7,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,],[-11,-27,-10,-27,-27,-8,-6,-4,-26,-19,-21,-25,-24,-20,-22,-23,-27,-17,-18,32,-7,-27,-27,-3,-2,-12,-9,-1,-5,]),u'TAG':([0,7,9,27,28,],[6,6,6,6,6,]),'$end':([0,1,3,6,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26,27,28,29,30,31,32,33,34,],[-27,-11,-27,-10,-27,-8,0,-6,-4,-26,-19,-21,-25,-24,-20,-22,-23,-27,-17,-18,-7,-27,-27,-3,-2,-12,-9,-1,-5,]),u'PROJECT':([0,7,9,27,28,],[5,5,5,5,5,]),u'GE':([2,4,5,6,8,],[-15,20,-14,-13,-16,]),u'LPAREN':([0,7,9,27,28,],[7,7,7,7,7,]),u'IN':([2,4,5,6,8,],[-15,21,-14,-13,-16,]),u'EQ':([2,4,5,6,8,],[-15,23,-14,-13,-16,]),u'AND':([0,1,3,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,],[-27,-11,-27,-10,-27,-27,-8,27,-6,-4,-26,-19,-21,-25,-24,-20,-22,-23,-27,-17,-18,27,-7,-27,-27,-3,-2,-12,-9,-1,-5,]),u'MATCHES':([2,4,5,6,8,],[-15,17,-14,-13,-16,]),u'CONTAINS':([2,4,5,6,8,],[-15,18,-14,-13,-16,]),u'LEQ':([2,4,5,6,8,],[-15,19,-14,-13,-16,]),u'NOT':([0,7,9,27,28,],[9,9,9,9,9,]),u'TYPE':([0,7,9,27,28,],[2,2,2,2,2,]),u'OR':([0,1,3,6,7,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,26,27,28,31,32,33,34,],[-27,-11,-27,-10,-27,-27,-8,-6,28,-26,-19,-21,-25,-24,-20,-22,-23,-27,-17,-18,-7,-27,-27,-12,-9,28,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {u'argument':([0,7,9,27,28,],[4,4,4,4,4,]),u'words':([0,3,7,9,22,27,28,],[1,14,1,1,31,1,1,]),u'operator':([4,],[22,]),u'E4':([0,7,9,27,28,],[10,10,10,10,10,]),u'E1':([0,7,],[11,25,]),u'E3':([0,7,9,27,28,],[12,12,26,12,34,]),u'E2':([0,7,27,],[13,13,33,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> E1","S'",1,None,None,None),
  (u'E1 -> E1 AND E2',u'E1',3,'p_E1_and','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',89),
  (u'E1 -> E2 PLUS_DESCENDANTS',u'E1',2,'p_E1_plus_d','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',94),
  (u'E1 -> E2 ONLY_FIRST',u'E1',2,'p_E1_only_f','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',99),
  (u'E1 -> E2',u'E1',1,'p_E1_E2','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',104),
  (u'E2 -> E2 OR E3',u'E2',3,'p_E2_or','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',109),
  (u'E2 -> E3',u'E2',1,'p_E2_E3','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',114),
  (u'E3 -> NOT E3',u'E3',2,'p_E3_not','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',119),
  (u'E3 -> E4',u'E3',1,'p_E3_E4','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',124),
  (u'E3 -> LPAREN E1 RPAREN',u'E3',3,'p_E3_paren','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',129),
  (u'E4 -> TAG',u'E4',1,'p_E4_tag','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',134),
  (u'E4 -> words',u'E4',1,'p_E4_words','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',139),
  (u'E4 -> argument operator words',u'E4',3,'p_E4_argument_operator_words','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',144),
  (u'argument -> TAG',u'argument',1,'p_argument_tag','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',151),
  (u'argument -> PROJECT',u'argument',1,'p_argument_project','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',156),
  (u'argument -> TYPE',u'argument',1,'p_argument_type','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',161),
  (u'argument -> UNIQUEID',u'argument',1,'p_argument_uniqueid','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',166),
  (u'operator -> EQ',u'operator',1,'p_operator_eq','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',171),
  (u'operator -> NEQ',u'operator',1,'p_operator_neq','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',176),
  (u'operator -> GEQ',u'operator',1,'p_operator_qeq','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',181),
  (u'operator -> LEQ',u'operator',1,'p_operator_leq','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',186),
  (u'operator -> LE',u'operator',1,'p_operator_le','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',191),
  (u'operator -> GE',u'operator',1,'p_operator_ge','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',196),
  (u'operator -> IN',u'operator',1,'p_operator_in','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',201),
  (u'operator -> CONTAINS',u'operator',1,'p_operator_contains','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',206),
  (u'operator -> MATCHES',u'operator',1,'p_operator_matches','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',211),
  (u'words -> TEXT words',u'words',2,'p_words','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',217),
  (u'words -> <empty>',u'words',0,'p_words_epsilon','/Users/bvsc/Dropbox/Projects/todoflow4/todoflow/querying/parser.py',222),
]
